name: Build dev container image
run-name: Docker build by @${{ github.actor }}
on: [push]
jobs:
  build-docker:
    steps:
      - name: Build docker image
        uses: devcontainers/ci@v0.2
        with:
          imageName: ghcr.io/rauljmz/devcontainer-serverless
          cacheFrom: ghcr.io/rauljmz/devcontainer-serverless
          push: always
